"""add cluster number

Revision ID: 017373089afb
Revises: db0747a3e070
Create Date: 2026-08-11 20:29:12.117011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017373089afb'
down_revision: Union[str, Sequence[str], None] = 'db0747a3e070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('cluster_number', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_clusters_cluster_number'), 'clusters', ['cluster_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clusters_cluster_number'), table_name='clusters')
    op.drop_column('clusters', 'cluster_number')
    # ### end Alembic commands ###
