"""create escalations table

Revision ID: 0fa3528ac4b0
Revises: 42747e4a94a9
Create Date: 2026-08-10 19:49:59.201024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa3528ac4b0'
down_revision: Union[str, Sequence[str], None] = '42747e4a94a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=False),
    sa.Column('from_role', sa.Enum('MANAGER', 'ASSISTANT_DEAN', 'ASSOCIATE_DEAN', 'DEAN', name='escalation_role'), nullable=False),
    sa.Column('to_role', sa.Enum('MANAGER', 'ASSISTANT_DEAN', 'ASSOCIATE_DEAN', 'DEAN', name='escalation_role'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_from_user_id'), 'escalations', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_escalations_grievance_id'), 'escalations', ['grievance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_escalations_grievance_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_from_user_id'), table_name='escalations')
    op.drop_table('escalations')
    # ### end Alembic commands ###
