"""add last reminder timestamp to grievances

Revision ID: 1b53222f19bb
Revises: f9323db44339
Create Date: 2026-08-16 13:16:06.370357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b53222f19bb'
down_revision: Union[str, Sequence[str], None] = 'f9323db44339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grievances', sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_grievances_last_reminder_at'), 'grievances', ['last_reminder_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grievances_last_reminder_at'), table_name='grievances')
    op.drop_column('grievances', 'last_reminder_at')
    # ### end Alembic commands ###
