"""create grievances table

Revision ID: 1ff86060fd5b
Revises: 5308dce131f9
Create Date: 2026-08-10 19:14:58.291345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff86060fd5b'
down_revision: Union[str, Sequence[str], None] = '5308dce131f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grievances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.String(length=30), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'AI_PROCESSING', 'PENDING_REVIEW', 'ASSIGNED', 'IN_PROGRESS', 'AWAITING_INFORMATION', 'ESCALATED', 'RESOLVED', 'CLOSED', 'REOPENED', name='grievance_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='grievance_priority'), nullable=False),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievances_applicant_id'), 'grievances', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_grievances_category_id'), 'grievances', ['category_id'], unique=False)
    op.create_index(op.f('ix_grievances_cluster_id'), 'grievances', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_grievances_grievance_id'), 'grievances', ['grievance_id'], unique=True)
    op.create_index(op.f('ix_grievances_status'), 'grievances', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grievances_status'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_grievance_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_cluster_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_category_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_applicant_id'), table_name='grievances')
    op.drop_table('grievances')
    # ### end Alembic commands ###
