"""add subject clusters and subjects

Revision ID: 24ed5081a3e4
Revises: fe83dc001625
Create Date: 2026-08-18 07:26:18.376348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24ed5081a3e4'
down_revision: Union[str, Sequence[str], None] = 'fe83dc001625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('assistant_dean_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assistant_dean_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_clusters_assistant_dean_id'), 'subject_clusters', ['assistant_dean_id'], unique=False)
    op.create_index(op.f('ix_subject_clusters_cluster_number'), 'subject_clusters', ['cluster_number'], unique=True)
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('subject_cluster_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_cluster_id'], ['subject_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=True)
    op.create_index(op.f('ix_subjects_subject_cluster_id'), 'subjects', ['subject_cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjects_subject_cluster_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_subject_clusters_cluster_number'), table_name='subject_clusters')
    op.drop_index(op.f('ix_subject_clusters_assistant_dean_id'), table_name='subject_clusters')
    op.drop_table('subject_clusters')
    # ### end Alembic commands ###
