"""create grievance status history table

Revision ID: 42747e4a94a9
Revises: 76d5a59851a6
Create Date: 2026-08-10 19:33:27.584226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '42747e4a94a9'
down_revision: Union[str, Sequence[str], None] = '76d5a59851a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'grievance_status_history',

        sa.Column(
            'id',
            sa.UUID(),
            nullable=False
        ),

        sa.Column(
            'grievance_id',
            sa.UUID(),
            nullable=False
        ),

        sa.Column(
            'previous_status',
            postgresql.ENUM(
                'SUBMITTED',
                'AI_PROCESSING',
                'PENDING_REVIEW',
                'ASSIGNED',
                'IN_PROGRESS',
                'AWAITING_INFORMATION',
                'ESCALATED',
                'RESOLVED',
                'CLOSED',
                'REOPENED',
                name='grievance_status',
                create_type=False
            ),
            nullable=True
        ),

        sa.Column(
            'new_status',
            postgresql.ENUM(
                'SUBMITTED',
                'AI_PROCESSING',
                'PENDING_REVIEW',
                'ASSIGNED',
                'IN_PROGRESS',
                'AWAITING_INFORMATION',
                'ESCALATED',
                'RESOLVED',
                'CLOSED',
                'REOPENED',
                name='grievance_status',
                create_type=False
            ),
            nullable=False
        ),

        sa.Column(
            'changed_by',
            sa.UUID(),
            nullable=False
        ),

        sa.Column(
            'reason',
            sa.Text(),
            nullable=True
        ),

        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False
        ),

        sa.ForeignKeyConstraint(
            ['changed_by'],
            ['users.id']
        ),

        sa.ForeignKeyConstraint(
            ['grievance_id'],
            ['grievances.id']
        ),

        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_grievance_status_history_changed_by'),
        'grievance_status_history',
        ['changed_by'],
        unique=False
    )

    op.create_index(
        op.f('ix_grievance_status_history_grievance_id'),
        'grievance_status_history',
        ['grievance_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grievance_status_history_grievance_id'), table_name='grievance_status_history')
    op.drop_index(op.f('ix_grievance_status_history_changed_by'), table_name='grievance_status_history')
    op.drop_table('grievance_status_history')
    # ### end Alembic commands ###
