"""create assignments table

Revision ID: 76d5a59851a6
Revises: 1ff86060fd5b
Create Date: 2026-08-10 19:22:37.428461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d5a59851a6'
down_revision: Union[str, Sequence[str], None] = '1ff86060fd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_assigned_by'), 'assignments', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_assignments_assigned_to'), 'assignments', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_assignments_grievance_id'), 'assignments', ['grievance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignments_grievance_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assigned_to'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assigned_by'), table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###
