"""create notifications table

Revision ID: 8379eb83afeb
Revises: e03e99b1c482
Create Date: 2026-08-10 20:01:40.054900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8379eb83afeb'
down_revision: Union[str, Sequence[str], None] = 'e03e99b1c482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.Enum('GRIEVANCE_SUBMITTED', 'GRIEVANCE_ASSIGNED', 'GRIEVANCE_ESCALATED', 'GRIEVANCE_RESOLVED', 'GRIEVANCE_CLOSED', 'INFORMATION_REQUESTED', 'SYSTEM', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_grievance_id'), 'notifications', ['grievance_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_grievance_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
