"""add phd registration number to users

Revision ID: 92ae695d7952
Revises: f7c8d9e012ab
Create Date: 2026-08-21 00:40:59.379062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92ae695d7952'
down_revision: Union[str, Sequence[str], None] = 'f7c8d9e012ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('request_group_id', sa.UUID(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADED', 'APPROVED', 'REJECTED', 'EXPIRED', 'CANCELLED', name='document_request_status'), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previous_grievance_status', sa.String(length=50), nullable=True),
    sa.Column('uploaded_document_id', sa.UUID(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('review_remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uploaded_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_requests_grievance_id'), 'document_requests', ['grievance_id'], unique=False)
    op.create_index(op.f('ix_document_requests_request_group_id'), 'document_requests', ['request_group_id'], unique=False)
    op.create_index(op.f('ix_document_requests_requested_by_id'), 'document_requests', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_document_requests_status'), 'document_requests', ['status'], unique=False)
    op.create_index(op.f('ix_document_requests_uploaded_document_id'), 'document_requests', ['uploaded_document_id'], unique=False)
    op.alter_column('categories', 'routing_type',
               existing_type=postgresql.ENUM('GRIEVANCE_CLUSTER', 'SUBJECT_ASSISTANT_DEAN', 'FIXED_AUTHORITY', name='category_routing_type'),
               nullable=False)
    op.add_column('users', sa.Column('phd_registration_number', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_users_phd_registration_number'), 'users', ['phd_registration_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phd_registration_number'), table_name='users')
    op.drop_column('users', 'phd_registration_number')
    op.alter_column('categories', 'routing_type',
               existing_type=postgresql.ENUM('GRIEVANCE_CLUSTER', 'SUBJECT_ASSISTANT_DEAN', 'FIXED_AUTHORITY', name='category_routing_type'),
               nullable=True)
    op.drop_index(op.f('ix_document_requests_uploaded_document_id'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_status'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_requested_by_id'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_request_group_id'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_grievance_id'), table_name='document_requests')
    op.drop_table('document_requests')
    # ### end Alembic commands ###
