"""add manager category review fields

Revision ID: 937d9cc2c52b
Revises: 1b53222f19bb
Create Date: 2026-08-17 17:53:08.325456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937d9cc2c52b'
down_revision: Union[str, Sequence[str], None] = '1b53222f19bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Add nullable columns first
    op.add_column(
        'grievances',
        sa.Column(
            'final_category_id',
            sa.UUID(),
            nullable=True
        )
    )

    op.add_column(
        'grievances',
        sa.Column(
            'category_reviewed',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )

    op.add_column(
        'grievances',
        sa.Column(
            'category_overridden',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )

    op.create_index(
        op.f('ix_grievances_final_category_id'),
        'grievances',
        ['final_category_id'],
        unique=False
    )

    op.create_foreign_key(
        'fk_grievances_final_category_id_categories',
        'grievances',
        'categories',
        ['final_category_id'],
        ['id']
    )

    # Remove server defaults after existing rows are populated
    op.alter_column(
        'grievances',
        'category_reviewed',
        server_default=None
    )

    op.alter_column(
        'grievances',
        'category_overridden',
        server_default=None
    )


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_constraint(
        'fk_grievances_final_category_id_categories',
        'grievances',
        type_='foreignkey'
    )

    op.drop_index(
        op.f('ix_grievances_final_category_id'),
        table_name='grievances'
    )

    op.drop_column(
        'grievances',
        'category_overridden'
    )

    op.drop_column(
        'grievances',
        'category_reviewed'
    )

    op.drop_column(
        'grievances',
        'final_category_id'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grievances', type_='foreignkey')
    op.drop_index(op.f('ix_grievances_final_category_id'), table_name='grievances')
    op.drop_column('grievances', 'category_overridden')
    op.drop_column('grievances', 'category_reviewed')
    op.drop_column('grievances', 'final_category_id')
    # ### end Alembic commands ###
