"""add grievance clusters

Revision ID: c343a0b7f7ff
Revises: 24ed5081a3e4
Create Date: 2026-08-18 07:54:51.467706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c343a0b7f7ff'
down_revision: Union[str, Sequence[str], None] = '24ed5081a3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grievance_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('associate_dean_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['associate_dean_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievance_clusters_associate_dean_id'), 'grievance_clusters', ['associate_dean_id'], unique=False)
    op.create_index(op.f('ix_grievance_clusters_cluster_number'), 'grievance_clusters', ['cluster_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grievance_clusters_cluster_number'), table_name='grievance_clusters')
    op.drop_index(op.f('ix_grievance_clusters_associate_dean_id'), table_name='grievance_clusters')
    op.drop_table('grievance_clusters')
    # ### end Alembic commands ###
