"""create ai processing records table

Revision ID: db0747a3e070
Revises: ce83363de6ed
Create Date: 2026-08-10 20:09:20.985044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db0747a3e070'
down_revision: Union[str, Sequence[str], None] = 'ce83363de6ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_processing_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('predicted_category_id', sa.UUID(), nullable=True),
    sa.Column('predicted_cluster_id', sa.UUID(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ai_processing_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ),
    sa.ForeignKeyConstraint(['predicted_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['predicted_cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_processing_records_grievance_id'), 'ai_processing_records', ['grievance_id'], unique=False)
    op.create_index(op.f('ix_ai_processing_records_predicted_category_id'), 'ai_processing_records', ['predicted_category_id'], unique=False)
    op.create_index(op.f('ix_ai_processing_records_predicted_cluster_id'), 'ai_processing_records', ['predicted_cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_processing_records_predicted_cluster_id'), table_name='ai_processing_records')
    op.drop_index(op.f('ix_ai_processing_records_predicted_category_id'), table_name='ai_processing_records')
    op.drop_index(op.f('ix_ai_processing_records_grievance_id'), table_name='ai_processing_records')
    op.drop_table('ai_processing_records')
    # ### end Alembic commands ###
