"""remove legacy clustering fields

Revision ID: fe83dc001625
Revises: 937d9cc2c52b
Create Date: 2026-08-17 19:10:52.118879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe83dc001625'
down_revision: Union[str, Sequence[str], None] = '937d9cc2c52b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_processing_records_predicted_cluster_id'), table_name='ai_processing_records')
    op.drop_constraint(op.f('ai_processing_records_predicted_cluster_id_fkey'), 'ai_processing_records', type_='foreignkey')
    op.drop_column('ai_processing_records', 'predicted_cluster_id')
    op.drop_index(op.f('ix_grievances_cluster_id'), table_name='grievances')
    op.drop_constraint(op.f('grievances_cluster_id_fkey'), 'grievances', type_='foreignkey')
    op.drop_column('grievances', 'cluster_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grievances', sa.Column('cluster_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('grievances_cluster_id_fkey'), 'grievances', 'clusters', ['cluster_id'], ['id'])
    op.create_index(op.f('ix_grievances_cluster_id'), 'grievances', ['cluster_id'], unique=False)
    op.add_column('ai_processing_records', sa.Column('predicted_cluster_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('ai_processing_records_predicted_cluster_id_fkey'), 'ai_processing_records', 'clusters', ['predicted_cluster_id'], ['id'])
    op.create_index(op.f('ix_ai_processing_records_predicted_cluster_id'), 'ai_processing_records', ['predicted_cluster_id'], unique=False)
    # ### end Alembic commands ###
